### ISSUE TITLE
README.rst: Typos

### ISSUE THREAD

**Issue by dongbohu** [greenelab/annotation-refinery#9]
I found a few typos in `README.rst`:

1. Line 19: `amon` should be `among`.

2. Line 33: `loaded to` probably should be `uploaded to`, `downloaded to` should be `downloaded from`.

3. Line 43: `this files` should be `this file`.

**Comment by rzelayafavila** [comment]
Resolved with https://github.com/greenelab/annotation-refinery/pull/8
